# Generated by Django 5.1.5 on 2025-01-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_steam_ID", models.CharField(max_length=25, null=True)),
                ("price", models.FloatField()),
                ("status_trade", models.BooleanField(default=True)),
                ("date_push_item", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
                ("trade_link", models.URLField(blank=True, default="")),
                ("count_buy", models.IntegerField(default=0)),
                ("count_sell", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=5)),
                ("inventory_json", models.JSONField(blank=True, default=dict)),
                ("steam_ID", models.CharField(max_length=17, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("telegram", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_status_st",
                    models.CharField(
                        choices=[
                            ("получен", "Получен"),
                            ("ожидает оплаты", "Ожидает оплаты"),
                            ("отменен", "Отменен"),
                        ],
                        default="ожидает оплаты",
                        max_length=15,
                    ),
                ),
                ("buyer_ID", models.CharField(max_length=17, null=True)),
                (
                    "item_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.itemst"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemst",
            name="user_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userst"
            ),
        ),
    ]
