# Generated by Django 5.1.5 on 2025-01-28 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemst",
            name="user_ID",
        ),
        migrations.RemoveField(
            model_name="tradest",
            name="item_ID",
        ),
        migrations.AddField(
            model_name="itemst",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="web.userst",
            ),
        ),
        migrations.AddField(
            model_name="tradest",
            name="date_push_trade",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tradest",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="web.itemst",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemst",
            name="item_steam_ID",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="itemst",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userst",
            name="count_buy",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userst",
            name="count_sell",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userst",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userst",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="userst",
            name="steam_ID",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="userst",
            name="telegram",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
